name: Deploy
on:
  workflow_dispatch:
    inputs:
      deployChannels:
        description: 'Channels to deploy'
        required: true

jobs:
  deploy_webhooks:
    name: Build and deploy webhooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build code
        run: npm run build

      - name: Run deploy code
        run: npm run deploy
        env:
          RESOURCES: https://discord.com/api/webhooks/${{ secrets.WEBHOOK_RESOURCES_ID }}/${{ secrets.WEBHOOK_RESOURCES_TOKEN }}
          RULES: https://discord.com/api/webhooks/${{ secrets.WEBHOOK_RULES_ID }}/${{ secrets.WEBHOOK_RULES_TOKEN }}
          USEFUL_SERVERS: https://discord.com/api/webhooks/${{ secrets.WEBHOOK_USEFUL_SERVERS_ID }}/${{ secrets.WEBHOOK_USEFUL_SERVERS_TOKEN }}
          HOW_TO_GET_HELP: https://discord.com/api/webhooks/${{ secrets.WEBHOOK_HOW_TO_GET_HELP_ID }}/${{ secrets.WEBHOOK_HOW_TO_GET_HELP_TOKEN }}
          HOW_TO_GIVE_HELP: https://discord.com/api/webhooks/${{ secrets.WEBHOOK_HOW_TO_GIVE_HELP_ID }}/${{ secrets.WEBHOOK_HOW_TO_GIVE_HELP_TOKEN }}
          WEBHOOK_AVATAR: ${{ secrets.WEBHOOK_AVATAR }}
          WEBHOOK_NAME: ${{ secrets.WEBHOOK_NAME }}
          DEPLOY_CHANNELS: ${{ github.event.inputs.deployChannels }}
